package com.asadali.codeanalyzer.tsql.keywords;

import java.util.HashSet;
import java.util.Set;

public class TSQLReservedKeywords {

	private static Set<String> reservedKeywordsSet = new HashSet<String>();

	static {

		reservedKeywordsSet.add("ADD");
		reservedKeywordsSet.add("ALL");
		reservedKeywordsSet.add("ALTER");
		reservedKeywordsSet.add("AND");
		reservedKeywordsSet.add("ANY");
		reservedKeywordsSet.add("AS");
		reservedKeywordsSet.add("ASC");
		reservedKeywordsSet.add("AUTHORIZATION");
		reservedKeywordsSet.add("BACKUP");
		reservedKeywordsSet.add("BEGIN");
		reservedKeywordsSet.add("BETWEEN");
		reservedKeywordsSet.add("BREAK");
		reservedKeywordsSet.add("BROWSE");
		reservedKeywordsSet.add("BULK");
		reservedKeywordsSet.add("BY");
		reservedKeywordsSet.add("CASCADE");
		reservedKeywordsSet.add("CASE");
		reservedKeywordsSet.add("CHECK");
		reservedKeywordsSet.add("CHECKPOINT");
		reservedKeywordsSet.add("CLOSE");
		reservedKeywordsSet.add("CLUSTERED");
		reservedKeywordsSet.add("COALESCE");
		reservedKeywordsSet.add("COLLATE");
		reservedKeywordsSet.add("COLUMN");
		reservedKeywordsSet.add("COMMIT");
		reservedKeywordsSet.add("COMPUTE");
		reservedKeywordsSet.add("CONSTRAINT");
		reservedKeywordsSet.add("CONTAINS");
		reservedKeywordsSet.add("CONTAINSTABLE");
		reservedKeywordsSet.add("CONTINUE");
		reservedKeywordsSet.add("CONVERT");
		reservedKeywordsSet.add("CREATE");
		reservedKeywordsSet.add("CROSS");
		reservedKeywordsSet.add("CURRENT");
		reservedKeywordsSet.add("CURRENT_DATE");
		reservedKeywordsSet.add("CURRENT_TIME");
		reservedKeywordsSet.add("CURRENT_TIMESTAMP");
		reservedKeywordsSet.add("CURRENT_USER");
		reservedKeywordsSet.add("CURSOR");
		reservedKeywordsSet.add("DATABASE");
		reservedKeywordsSet.add("DBCC");
		reservedKeywordsSet.add("DEALLOCATE");
		reservedKeywordsSet.add("DECLARE");
		reservedKeywordsSet.add("DEFAULT");
		reservedKeywordsSet.add("DELETE");
		reservedKeywordsSet.add("DENY");
		reservedKeywordsSet.add("DESC");
		reservedKeywordsSet.add("DISK");
		reservedKeywordsSet.add("DISTINCT");
		reservedKeywordsSet.add("DISTRIBUTED");
		reservedKeywordsSet.add("DOUBLE");
		reservedKeywordsSet.add("DROP");
		reservedKeywordsSet.add("DUMP");
		reservedKeywordsSet.add("ELSE");
		reservedKeywordsSet.add("END");
		reservedKeywordsSet.add("ERRLVL");
		reservedKeywordsSet.add("ESCAPE");
		reservedKeywordsSet.add("EXCEPT");
		reservedKeywordsSet.add("EXEC");
		reservedKeywordsSet.add("EXECUTE");
		reservedKeywordsSet.add("EXISTS");
		reservedKeywordsSet.add("EXIT");
		reservedKeywordsSet.add("EXTERNAL");
		reservedKeywordsSet.add("FETCH");
		reservedKeywordsSet.add("FILE");
		reservedKeywordsSet.add("FILLFACTOR");
		reservedKeywordsSet.add("FOR");
		reservedKeywordsSet.add("FOREIGN");
		reservedKeywordsSet.add("FREETEXT");
		reservedKeywordsSet.add("FREETEXTTABLE");
		reservedKeywordsSet.add("FROM");
		reservedKeywordsSet.add("FULL");
		reservedKeywordsSet.add("FUNCTION");
		reservedKeywordsSet.add("GOTO");
		reservedKeywordsSet.add("GRANT");
		reservedKeywordsSet.add("GROUP");
		reservedKeywordsSet.add("HAVING");
		reservedKeywordsSet.add("HOLDLOCK");
		reservedKeywordsSet.add("IDENTITY");
		reservedKeywordsSet.add("IDENTITY_INSERT");
		reservedKeywordsSet.add("IDENTITYCOL");
		reservedKeywordsSet.add("IF");
		reservedKeywordsSet.add("IN");
		reservedKeywordsSet.add("INDEX");
		reservedKeywordsSet.add("INNER");
		reservedKeywordsSet.add("INSERT");
		reservedKeywordsSet.add("INTERSECT");
		reservedKeywordsSet.add("INTO");
		reservedKeywordsSet.add("IS");
		reservedKeywordsSet.add("JOIN");
		reservedKeywordsSet.add("KEY");
		reservedKeywordsSet.add("KILL");
		reservedKeywordsSet.add("LEFT");
		reservedKeywordsSet.add("LIKE");
		reservedKeywordsSet.add("LINENO");
		reservedKeywordsSet.add("LOAD");
		reservedKeywordsSet.add("MERGE");
		reservedKeywordsSet.add("NATIONAL");
		reservedKeywordsSet.add("NOCHECK");
		reservedKeywordsSet.add("NONCLUSTERED");
		reservedKeywordsSet.add("NOT");
		reservedKeywordsSet.add("NULL");
		reservedKeywordsSet.add("NULLIF");
		reservedKeywordsSet.add("OF");
		reservedKeywordsSet.add("OFF");
		reservedKeywordsSet.add("OFFSETS");
		reservedKeywordsSet.add("ON");
		reservedKeywordsSet.add("OPEN");
		reservedKeywordsSet.add("OPENDATASOURCE");
		reservedKeywordsSet.add("OPENQUERY");
		reservedKeywordsSet.add("OPENROWSET");
		reservedKeywordsSet.add("OPENXML");
		reservedKeywordsSet.add("OPTION");
		reservedKeywordsSet.add("OR");
		reservedKeywordsSet.add("ORDER");
		reservedKeywordsSet.add("OUTER");
		reservedKeywordsSet.add("OVER");
		reservedKeywordsSet.add("PERCENT");
		reservedKeywordsSet.add("PIVOT");
		reservedKeywordsSet.add("PLAN");
		reservedKeywordsSet.add("PRECISION");
		reservedKeywordsSet.add("PRIMARY");
		reservedKeywordsSet.add("PRINT");
		reservedKeywordsSet.add("PROC");
		reservedKeywordsSet.add("PROCEDURE");
		reservedKeywordsSet.add("PUBLIC");
		reservedKeywordsSet.add("RAISERROR");
		reservedKeywordsSet.add("READ");
		reservedKeywordsSet.add("READTEXT");
		reservedKeywordsSet.add("RECONFIGURE");
		reservedKeywordsSet.add("REFERENCES");
		reservedKeywordsSet.add("REPLICATION");
		reservedKeywordsSet.add("RESTORE");
		reservedKeywordsSet.add("RESTRICT");
		reservedKeywordsSet.add("RETURN");
		reservedKeywordsSet.add("REVERT");
		reservedKeywordsSet.add("REVOKE");
		reservedKeywordsSet.add("RIGHT");
		reservedKeywordsSet.add("ROLLBACK");
		reservedKeywordsSet.add("ROWCOUNT");
		reservedKeywordsSet.add("ROWGUIDCOL");
		reservedKeywordsSet.add("RULE");
		reservedKeywordsSet.add("SAVE");
		reservedKeywordsSet.add("SCHEMA");
		reservedKeywordsSet.add("SECURITYAUDIT");
		reservedKeywordsSet.add("SELECT");
		reservedKeywordsSet.add("SEMANTICKEYPHRASETABLE");
		reservedKeywordsSet.add("SEMANTICSIMILARITYDETAILSTABLE");
		reservedKeywordsSet.add("SEMANTICSIMILARITYTABLE");
		reservedKeywordsSet.add("SESSION_USER");
		reservedKeywordsSet.add("SET");
		reservedKeywordsSet.add("SETUSER");
		reservedKeywordsSet.add("SHUTDOWN");
		reservedKeywordsSet.add("SOME");
		reservedKeywordsSet.add("STATISTICS");
		reservedKeywordsSet.add("SYSTEM_USER");
		reservedKeywordsSet.add("TABLE");
		reservedKeywordsSet.add("TABLESAMPLE");
		reservedKeywordsSet.add("TEXTSIZE");
		reservedKeywordsSet.add("THEN");
		reservedKeywordsSet.add("TO");
		reservedKeywordsSet.add("TOP");
		reservedKeywordsSet.add("TRAN");
		reservedKeywordsSet.add("TRANSACTION");
		reservedKeywordsSet.add("TRIGGER");
		reservedKeywordsSet.add("TRUNCATE");
		reservedKeywordsSet.add("TRY_CONVERT");
		reservedKeywordsSet.add("TSEQUAL");
		reservedKeywordsSet.add("UNION");
		reservedKeywordsSet.add("UNIQUE");
		reservedKeywordsSet.add("UNPIVOT");
		reservedKeywordsSet.add("UPDATE");
		reservedKeywordsSet.add("UPDATETEXT");
		reservedKeywordsSet.add("USE");
		reservedKeywordsSet.add("USER");
		reservedKeywordsSet.add("VALUES");
		reservedKeywordsSet.add("VARYING");
		reservedKeywordsSet.add("VIEW");
		reservedKeywordsSet.add("WAITFOR");
		reservedKeywordsSet.add("WHEN");
		reservedKeywordsSet.add("WHERE");
		reservedKeywordsSet.add("WHILE");
		reservedKeywordsSet.add("WITH");
		reservedKeywordsSet.add("WITHIN GROUP");
		reservedKeywordsSet.add("WRITETEXT");

	}
	
	public static boolean checkIfReserved(String keyword) {
		if(keyword == null) {
			return false;
		} else {				
			keyword = keyword.toUpperCase();
			return reservedKeywordsSet.contains(keyword);
		}
	}
}
